Scikit Learn is a very popular library in python. Scikit learn is a free and open source python library mainly used for the creation of Machine Learning applications.

It is considered to be one of the most important libraries in all of the Python libraries.

Scikit learn is usually used alongside other popular ibraries like Numpy, Pandas, even Matplotlib to add functionality.

It was originally called scikits.learn and was initially developed by David Cournapeau as a Google summer of code project in 2007.Scikit learn was publicly released in 2010 with a v0.1 beta version which is very helpful for the programmers.

The latest version is 0.23.1 of the scikit learn is released in May 2020. 

Scikit learn in python is mostly used in python for the modeling. It not focused on loading the data.

To use sklearn library we need to install Python, Numpy, Pandas, Matplotlib, Scipy, joblib in our system. 

The benefit of scikit learn are :
<li>
<li>Open source</li>
<li>Easy to use</li>
<li>Free</li>
<li>Properly documented</li>
<li>Versatile used</li>
</li>

    
install : pip install -U scikit-learn  

import : import sklearn

<h1>Advantages:</h1>
    
<br>
<ol>    
<li>The scikit learn library is a user-friendly and handy tool it can do multiple things such as prediction of customer behavior, creation of neuroimage, etc.</li>
<li>It is easy to use and free to use.</li>
<li>Scikit learn library is updated by the contributor and by the international online community.</li>
<li>Scikit learn library provides the API documentation for the user who wants to integrate algorithm with his platform.</li>
<li>The scikit learn library is spread under the BSD license which makes it free with legal and licensing restrictions the user can use it anytime without any hesitation and run this library on their platform.</li>
<li>In scikit learn the documentation in the task is done in the proper way and this library is very extensive.</li>
    </ol>

# Loading Data

In [1]:
from sklearn.datasets import load_iris
df = load_iris()
x = df.data
y = df.target

features_names = df.feature_names
target_names = df.target_names

print("Features name :", features_names)
print("Target_naems : ", target_names)
print()
print("First 5 rows :", x[:5])

Features name : ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Target_naems :  ['setosa' 'versicolor' 'virginica']

First 5 rows : [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


# Splitting the Dataset

In [2]:

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.30, random_state = 0)
print(x_train.shape)
print(y_train.shape)

print(x_test.shape)
print(y_test.shape)

(105, 4)
(105,)
(45, 4)
(45,)


# Train the Model using KNN Algorithm

In [3]:
from sklearn.neighbors import KNeighborsClassifier
model = KNeighborsClassifier(n_neighbors = 4)
model.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=4)

In [4]:
#Predict Output

y_pred = model.predict(x_test)


In [5]:
# Check accuracy
from sklearn import metrics
print("Accuracy is :", metrics.accuracy_score(y_test, y_pred) )
# print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

Accuracy is : 0.9777777777777777


In [6]:
# Predict output

sample = [[5, 5, 3, 2], [2, 4, 3, 5]]
preds = model.predict(sample)
# print(preds)
pred_species = [df.target_names[p] for p in preds] 

print("Predictions:", pred_species)

Predictions: ['setosa', 'versicolor']


# Linear Regression Model

In [7]:
from sklearn.linear_model import LinearRegression
model = LinearRegression()

model.fit(x,y)


LinearRegression()

In [8]:
print(model.coef_)
print(model.intercept_)

[-0.11190585 -0.04007949  0.22864503  0.60925205]
0.18649524720624888


In [9]:
y_pred = model.predict(x_test)
y_pred

array([ 2.0535133 ,  0.95071742, -0.15536734,  1.79046937, -0.04448632,
        2.24422636, -0.03329807,  1.30098933,  1.26376188,  1.09825476,
        1.5330279 ,  1.28482413,  1.19738107,  1.31252984,  1.31522353,
       -0.12510134,  1.34161032,  1.20394697,  0.03198734, -0.033167  ,
        1.78646464,  1.38236471,  0.06935286,  0.01983243,  1.57460622,
       -0.12206239,  0.14159972,  1.15164973,  0.8985638 ,  0.10022859,
        1.70025272,  1.40474588, -0.07087544,  1.60064541,  1.97884189,
        1.24103868, -0.03219801,  1.54773844,  1.28019945,  1.0789172 ,
        1.84227394, -0.04862768,  1.85746781,  0.21807105, -0.10127251])

In [10]:
# Model Evaluation
import numpy as np
from sklearn import metrics
print(metrics.mean_squared_error(y_test,y_pred))
print(metrics.mean_absolute_error(y_test,y_pred))
print(np.sqrt(metrics.mean_squared_error(y_test,y_pred)))

0.05425047759995535
0.18971361203692835
0.23291731923572223


# KMeans Clustering Model

In [11]:
from sklearn.cluster import KMeans
import numpy as np
from sklearn.datasets import load_diabetes

In [12]:
df = load_diabetes()
x  = df.data
y = df.target
print("First 5 rows of X :", x[:5])
df.data.shape

First 5 rows of X : [[ 0.03807591  0.05068012  0.06169621  0.02187235 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990842 -0.01764613]
 [-0.00188202 -0.04464164 -0.05147406 -0.02632783 -0.00844872 -0.01916334
   0.07441156 -0.03949338 -0.06832974 -0.09220405]
 [ 0.08529891  0.05068012  0.04445121 -0.00567061 -0.04559945 -0.03419447
  -0.03235593 -0.00259226  0.00286377 -0.02593034]
 [-0.08906294 -0.04464164 -0.01159501 -0.03665645  0.01219057  0.02499059
  -0.03603757  0.03430886  0.02269202 -0.00936191]
 [ 0.00538306 -0.04464164 -0.03638469  0.02187235  0.00393485  0.01559614
   0.00814208 -0.00259226 -0.03199144 -0.04664087]]


(442, 10)

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size = 0.30, random_state = 1)


In [14]:
# kmeans = KMeans(n_clusters = 10, random_state = 0)
# clusters = kmeans.fit_predict(df.data)
# kmeans.cluster_centers_.shape

cluster =  KMeans(n_clusters = 10)  
cluster.fit(x[:50, :])

print("The number of clusters are: ", cluster.labels_)  

The number of clusters are:  [9 2 9 0 4 1 5 7 9 4 1 5 2 5 2 7 4 7 4 4 4 5 4 8 4 0 1 4 2 6 4 2 9 3 2 3 4
 4 7 0 7 1 0 3 9 5 4 1 5 0]



# Spectral Clustering

In [15]:
#Spectral clustering model for Diabetes dataset
from sklearn.cluster import SpectralClustering  
cluster =  SpectralClustering(n_clusters = 10)  
cluster.fit(x[:50, :])  
  
print("The number of clusters are: ", cluster.labels_)  

The number of clusters are:  [7 2 7 3 6 5 4 6 7 3 1 7 2 3 2 6 8 6 1 9 1 4 8 0 5 3 1 8 9 0 8 9 7 9 9 9 8
 9 6 3 6 1 4 9 7 4 5 5 4 3]


# Support Vector Machine

In [16]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score
model = SVC(kernel="linear", random_state=0)
model.fit(x_train , y_train)
pred = model.predict(x_test)


accuracy = accuracy_score(y_test , pred)
print(accuracy) 

0.007518796992481203


# Model Persistence

In [17]:
# from sklearn.externals import joblib
import joblib
from joblib import dump,load
joblib.dump(model, 'iris_classifier_knn.joblib')

['iris_classifier_knn.joblib']

In [18]:
joblib.load('iris_classifier_knn.joblib')

SVC(kernel='linear', random_state=0)